import requests
import random
import re
import string
from config import SHORT_URL, SHORT_API, MESSAGES
from pyrogram import Client, filters
from pyrogram.types import Message, InlineKeyboardMarkup, InlineKeyboardButton, CallbackQuery, InputMediaPhoto
from pyrogram.errors.pyromod import ListenerTimeout
from helper.helper_func import force_sub

# ✅ In-memory cache — keyed by (active shortner name, url) so switching shortners
# never serves a link generated by a different provider.
shortened_urls_cache = {}

NAME_RE = re.compile(r'^[A-Za-z0-9_\-]{1,20}$')

def generate_random_alphanumeric():
    characters = string.ascii_letters + string.digits
    return ''.join(random.choice(characters) for _ in range(8))

#===============================================================#
# Helpers — multi-shortner support
#===============================================================#

def get_active_shortener(client):
    """Return the config dict {url, api, tutorial_link} of the currently active shortner, or None."""
    shorteners = getattr(client, 'shorteners', {}) or {}
    active = getattr(client, 'active_shortener', None)
    if active and active in shorteners:
        return shorteners[active]
    return None

async def save_shorteners(client):
    """Persist client.shorteners + client.active_shortener to the DB and refresh the legacy mirror attrs."""
    await client.mongodb.update_shortner_setting('shorteners', client.shorteners, client.bot_id)
    await client.mongodb.update_shortner_setting('active', client.active_shortener, client.bot_id)
    sync_mirror(client)

def sync_mirror(client):
    """Keep client.short_url/short_api/tutorial_link mirroring the active shortner (used by settings.py etc.)."""
    active_cfg = get_active_shortener(client) or {}
    client.short_url = active_cfg.get('url', SHORT_URL)
    client.short_api = active_cfg.get('api', SHORT_API)
    client.tutorial_link = active_cfg.get('tutorial_link', "")

#===============================================================#

def _shorten_with_config(url, cfg, cache_key):
    """Shared shortening logic — takes an explicit {url, api, ...} config
    rather than reading it off the client, so it works for both the regular
    active shortner and the auto-mode cycle."""
    if cache_key in shortened_urls_cache:
        return shortened_urls_cache[cache_key]

    try:
        alias = generate_random_alphanumeric()
        short_url = cfg.get('url', SHORT_URL)
        short_api = cfg.get('api', SHORT_API)

        api_url = f"https://{short_url}/api?api={short_api}&url={url}&alias={alias}"
        response = requests.get(api_url)
        rjson = response.json()

        if rjson.get("status") == "success" and response.status_code == 200:
            short_link = rjson.get("shortenedUrl", url)
            shortened_urls_cache[cache_key] = short_link
            return short_link
    except Exception as e:
        print(f"[Shortener Error] {e}")

    return None  # fallback — caller should deliver file directly

def get_short(url, client):

    # Check if shortner is enabled
    shortner_enabled = getattr(client, 'shortner_enabled', True)
    if not shortner_enabled:
        return None  # shortner disabled — caller will deliver file directly

    active_name = getattr(client, 'active_shortener', None)
    active_cfg = get_active_shortener(client)
    if not active_cfg:
        return None  # no shortner configured — caller will deliver file directly

    cache_key = f"{active_name}:{url}"
    return _shorten_with_config(url, active_cfg, cache_key)

#===============================================================#
# Auto-mode shortner support
#===============================================================#

def get_auto_shorteners(client):
    """Return this bot's ordered list of auto-mode shortner configs."""
    return getattr(client, 'auto_shorteners', []) or []

def get_auto_short(url, cfg, index):
    """Shorten `url` using the auto-mode shortner at position `index` (for cache keying only)."""
    cache_key = f"auto:{index}:{cfg.get('url', '')}:{url}"
    return _shorten_with_config(url, cfg, cache_key)

#===============================================================#

@Client.on_message(filters.command('shortner') & filters.private)
async def shortner_command(client: Client, message: Message):
    await shortner_panel(client, message)

#===============================================================#

async def shortner_panel(client, query_or_message):
    shorteners = getattr(client, 'shorteners', {}) or {}
    active_name = getattr(client, 'active_shortener', None)
    active_cfg = get_active_shortener(client)
    shortner_enabled = getattr(client, 'shortner_enabled', True)

    # Check if the active shortner is working (only if enabled + configured)
    if shortner_enabled and active_cfg:
        try:
            test_response = requests.get(
                f"https://{active_cfg.get('url', SHORT_URL)}/api?api={active_cfg.get('api', SHORT_API)}&url=https://google.com&alias=test",
                timeout=5
            )
            status = "✓ ᴡᴏʀᴋɪɴɢ" if test_response.status_code == 200 else "✗ ɴᴏᴛ ᴡᴏʀᴋɪɴɢ"
        except:
            status = "✗ ɴᴏᴛ ᴡᴏʀᴋɪɴɢ"
    elif not active_cfg:
        status = "✗ ɴᴏɴᴇ ᴄᴏɴꜰɪɢᴜʀᴇᴅ"
    else:
        status = "✗ ᴅɪsᴀʙʟᴇᴅ"

    enabled_text = "✓ ᴇɴᴀʙʟᴇᴅ" if shortner_enabled else "✗ ᴅɪsᴀʙʟᴇᴅ"
    toggle_text = "✗ ᴏғғ" if shortner_enabled else "✓ ᴏɴ"

    if shorteners:
        list_lines = []
        for name in shorteners:
            marker = "✓" if name == active_name else "•"
            list_lines.append(f"{marker} `{name}` — `{shorteners[name].get('url', '?')}`")
        shorteners_display = "\n".join(list_lines)
    else:
        shorteners_display = "_ɴᴏ ꜱʜᴏʀᴛɴᴇʀꜱ ᴀᴅᴅᴇᴅ ʏᴇᴛ_"

    active_url = active_cfg.get('url', 'ɴᴏᴛ ꜱᴇᴛ') if active_cfg else 'ɴᴏᴛ ꜱᴇᴛ'
    active_api = active_cfg.get('api', '') if active_cfg else ''
    active_tut = active_cfg.get('tutorial_link', 'ɴᴏᴛ ꜱᴇᴛ') if active_cfg else 'ɴᴏᴛ ꜱᴇᴛ'

    msg = f"""<blockquote>✦ 𝗦𝗛𝗢𝗥𝗧𝗡𝗘𝗥 𝗦𝗘𝗧𝗧𝗜𝗡𝗚𝗦</blockquote>
**<u>ᴀᴄᴛɪᴠᴇ ꜱʜᴏʀᴛɴᴇʀ:</u>**
<blockquote>›› **ꜱᴛᴀᴛᴜꜱ:** {enabled_text}
›› **ɴᴀᴍᴇ:** `{active_name or 'ɴᴏɴᴇ'}`
›› **ᴜʀʟ:** `{active_url}`
›› **ᴀᴘɪ:** `{(active_api[:20] + '...') if active_api else 'ɴᴏᴛ ꜱᴇᴛ'}`
›› **ᴛᴜᴛᴏʀɪᴀʟ ʟɪɴᴋ:** `{active_tut}`
›› **ᴀᴘɪ ꜱᴛᴀᴛᴜꜱ:** {status}</blockquote>

**<u>ᴀʟʟ ꜱʜᴏʀᴛɴᴇʀꜱ ({len(shorteners)}):</u>**
<blockquote>{shorteners_display}</blockquote>

<blockquote>**≡ ᴜꜱᴇ ᴛʜᴇ ʙᴜᴛᴛᴏɴꜱ ʙᴇʟᴏᴡ ᴛᴏ ᴄᴏɴꜰɪɢᴜʀᴇ ʏᴏᴜʀ ꜱʜᴏʀᴛɴᴇʀꜱ!**</blockquote>"""

    reply_markup = InlineKeyboardMarkup([
        [InlineKeyboardButton(f'• {toggle_text} ꜱʜᴏʀᴛɴᴇʀ •', 'toggle_shortner'), InlineKeyboardButton('• ᴀᴅᴅ ꜱʜᴏʀᴛɴᴇʀ •', 'add_shortner')],
        [InlineKeyboardButton('• ꜱᴡɪᴛᴄʜ ꜱʜᴏʀᴛɴᴇʀ •', 'switch_shortner'), InlineKeyboardButton('• ʀᴇᴍᴏᴠᴇ ꜱʜᴏʀᴛɴᴇʀ •', 'rm_shortner')],
        [InlineKeyboardButton('• ꜱᴇᴛ ᴛᴜᴛᴏʀɪᴀʟ ʟɪɴᴋ •', 'set_tutorial_link'), InlineKeyboardButton('• ᴛᴇꜱᴛ ꜱʜᴏʀᴛɴᴇʀ •', 'test_shortner')],
        [InlineKeyboardButton('• 🔁 ᴀᴜᴛᴏ ᴍᴏᴅᴇ •', 'auto_shortner')],
        [InlineKeyboardButton('◂ ʙᴀᴄᴋ ᴛᴏ ꜱᴇᴛᴛɪɴɢꜱ', 'settings')] if hasattr(query_or_message, 'message') else []
    ])

    image_url = MESSAGES.get("SHORT", "https://telegra.ph/file/8aaf4df8c138c6685dcee-05d3b183d4978ec347.jpg")

    if hasattr(query_or_message, 'message'):
        await query_or_message.message.edit_media(
            media=InputMediaPhoto(media=image_url, caption=msg),
            reply_markup=reply_markup
        )
    else:
        await query_or_message.reply_photo(photo=image_url, caption=msg, reply_markup=reply_markup)


#===============================================================#

@Client.on_callback_query(filters.regex("^shortner$"))
async def shortner_callback(client, query):
    if not query.from_user.id in client.admins:
        return await query.answer('❌ ᴏɴʟʏ ᴀᴅᴍɪɴꜱ ᴄᴀɴ ᴜꜱᴇ ᴛʜɪꜱ!', show_alert=True)
    await query.answer()
    await shortner_panel(client, query)

#===============================================================#

@Client.on_callback_query(filters.regex("^toggle_shortner$"))
async def toggle_shortner(client: Client, query: CallbackQuery):
    if not query.from_user.id in client.admins:
        return await query.answer('❌ ᴏɴʟʏ ᴀᴅᴍɪɴꜱ ᴄᴀɴ ᴜꜱᴇ ᴛʜɪꜱ!', show_alert=True)
    current_status = getattr(client, 'shortner_enabled', True)
    new_status = not current_status
    client.shortner_enabled = new_status

    await client.mongodb.set_shortner_status(new_status, client.bot_id)

    status_text = "ᴇɴᴀʙʟᴇᴅ" if new_status else "ᴅɪsᴀʙʟᴇᴅ"
    await query.answer(f"✓ ꜱʜᴏʀᴛɴᴇʀ {status_text}!")

    await shortner_panel(client, query)

#===============================================================#

@Client.on_callback_query(filters.regex("^add_shortner$"))
async def add_shortner(client: Client, query: CallbackQuery):
    if not query.from_user.id in client.admins:
        return await query.answer('❌ ᴏɴʟʏ ᴀᴅᴍɪɴꜱ ᴄᴀɴ ᴜꜱᴇ ᴛʜɪꜱ!', show_alert=True)

    await query.answer()

    msg = f"""<blockquote>**ᴀᴅᴅ / ᴇᴅɪᴛ ᴀ ꜱʜᴏʀᴛɴᴇʀ:**</blockquote>
**ᴄᴜʀʀᴇɴᴛ ꜱʜᴏʀᴛɴᴇʀꜱ:** `{len(getattr(client, 'shorteners', {}))}`

__<blockquote>**≡ ꜱᴇɴᴅ ᴛʜᴇ ɴᴇᴡ ꜱʜᴏʀᴛɴᴇʀ ɪɴ ᴛʜɪꜱ ꜰᴏʀᴍᴀᴛ ɪɴ ᴛʜᴇ ɴᴇxᴛ 90 ꜱᴇᴄᴏɴᴅꜱ!**</blockquote>__

**ꜰᴏʀᴍᴀᴛ:** `name url api tutorial_link`
**ᴇxᴀᴍᴘʟᴇ:** `gplinks gplinks.in 9435894656863495834957348 https://t.me/How_to_Download_7x/26`

**ɴᴏᴛᴇ:** ɴᴀᴍᴇ ᴍᴜꜱᴛ ʙᴇ ʟᴇᴛᴛᴇʀꜱ/ɴᴜᴍʙᴇʀꜱ ᴏɴʟʏ (ɴᴏ ꜱᴘᴀᴄᴇꜱ). ꜱᴇɴᴅɪɴɢ ᴀɴ ᴇxɪꜱᴛɪɴɢ ɴᴀᴍᴇ ᴡɪʟʟ ᴏᴠᴇʀᴡʀɪᴛᴇ ɪᴛ."""

    await query.message.edit_text(msg)
    try:
        res = await client.listen(user_id=query.from_user.id, filters=filters.text, timeout=90)
        response_text = res.text.strip()

        parts = response_text.split()
        if len(parts) == 4:
            name, raw_url, api, tutorial_link = parts
            name = name.lower()
            new_url = raw_url.replace('https://', '').replace('http://', '').replace('/', '')

            valid = (
                NAME_RE.match(name)
                and new_url and '.' in new_url
                and api and len(api) > 10
                and (tutorial_link.startswith('https://') or tutorial_link.startswith('http://'))
            )

            if valid:
                if not hasattr(client, 'shorteners'):
                    client.shorteners = {}
                client.shorteners[name] = {'url': new_url, 'api': api, 'tutorial_link': tutorial_link}

                # First shortner added automatically becomes active
                if not getattr(client, 'active_shortener', None):
                    client.active_shortener = name

                shortened_urls_cache.clear()
                await save_shorteners(client)

                await query.message.edit_text(
                    f"**✓ ꜱʜᴏʀᴛɴᴇʀ `{name}` ꜱᴀᴠᴇᴅ ꜱᴜᴄᴄᴇꜱꜱꜰᴜʟʟʏ!**\n\n**ᴜʀʟ:** `{new_url}`\n**ᴀᴄᴛɪᴠᴇ:** `{client.active_shortener}`",
                    reply_markup=InlineKeyboardMarkup([[InlineKeyboardButton('◂ ʙᴀᴄᴋ', 'shortner')]])
                )
            else:
                await query.message.edit_text("**✗ ɪɴᴠᴀʟɪᴅ ꜰᴏʀᴍᴀᴛ! ᴄʜᴇᴄᴋ ɴᴀᴍᴇ/ᴜʀʟ/ᴀᴘɪ/ᴛᴜᴛᴏʀɪᴀʟ ʟɪɴᴋ.**",
                                              reply_markup=InlineKeyboardMarkup([[InlineKeyboardButton('◂ ʙᴀᴄᴋ', 'shortner')]]))
        else:
            await query.message.edit_text("**✗ ɪɴᴠᴀʟɪᴅ ꜰᴏʀᴍᴀᴛ! ᴜꜱᴇ: `name url api tutorial_link`**",
                                          reply_markup=InlineKeyboardMarkup([[InlineKeyboardButton('◂ ʙᴀᴄᴋ', 'shortner')]]))
    except ListenerTimeout:
        await query.message.edit_text("**⏰ ᴛɪᴍᴇᴏᴜᴛ! ᴛʀʏ ᴀɢᴀɪɴ.**",
                                    reply_markup=InlineKeyboardMarkup([[InlineKeyboardButton('◂ ʙᴀᴄᴋ', 'shortner')]]))

#===============================================================#

@Client.on_callback_query(filters.regex("^switch_shortner$"))
async def switch_shortner(client: Client, query: CallbackQuery):
    if not query.from_user.id in client.admins:
        return await query.answer('❌ ᴏɴʟʏ ᴀᴅᴍɪɴꜱ ᴄᴀɴ ᴜꜱᴇ ᴛʜɪꜱ!', show_alert=True)

    await query.answer()

    shorteners = getattr(client, 'shorteners', {}) or {}
    if not shorteners:
        return await query.message.edit_text("**✗ ɴᴏ ꜱʜᴏʀᴛɴᴇʀꜱ ᴀᴅᴅᴇᴅ ʏᴇᴛ! ᴀᴅᴅ ᴏɴᴇ ꜰɪʀꜱᴛ.**",
                                             reply_markup=InlineKeyboardMarkup([[InlineKeyboardButton('◂ ʙᴀᴄᴋ', 'shortner')]]))

    active_name = getattr(client, 'active_shortener', None)
    listing = "\n".join(f"{'✓' if n == active_name else '•'} `{n}`" for n in shorteners)
    msg = f"""<blockquote>**ꜱᴡɪᴛᴄʜ ᴀᴄᴛɪᴠᴇ ꜱʜᴏʀᴛɴᴇʀ:**</blockquote>
**ᴀᴠᴀɪʟᴀʙʟᴇ ꜱʜᴏʀᴛɴᴇʀꜱ:**
{listing}

__ꜱᴇɴᴅ ᴛʜᴇ ɴᴀᴍᴇ ᴏꜰ ᴛʜᴇ ꜱʜᴏʀᴛɴᴇʀ ᴛᴏ ᴀᴄᴛɪᴠᴀᴛᴇ ɪɴ ᴛʜᴇ ɴᴇxᴛ 60 ꜱᴇᴄᴏɴᴅꜱ!__"""

    await query.message.edit_text(msg)
    try:
        res = await client.listen(user_id=query.from_user.id, filters=filters.text, timeout=60)
        name = res.text.strip().lower()
        if name not in shorteners:
            return await query.message.edit_text(f"**✗ ꜱʜᴏʀᴛɴᴇʀ `{name}` ɴᴏᴛ ꜰᴏᴜɴᴅ!**",
                                                 reply_markup=InlineKeyboardMarkup([[InlineKeyboardButton('◂ ʙᴀᴄᴋ', 'shortner')]]))
        client.active_shortener = name
        await save_shorteners(client)
        await query.message.edit_text(f"**✓ ꜱᴡɪᴛᴄʜᴇᴅ ᴛᴏ ꜱʜᴏʀᴛɴᴇʀ `{name}`!**",
                                      reply_markup=InlineKeyboardMarkup([[InlineKeyboardButton('◂ ʙᴀᴄᴋ', 'shortner')]]))
    except ListenerTimeout:
        await query.message.edit_text("**⏰ ᴛɪᴍᴇᴏᴜᴛ! ᴛʀʏ ᴀɢᴀɪɴ.**",
                                    reply_markup=InlineKeyboardMarkup([[InlineKeyboardButton('◂ ʙᴀᴄᴋ', 'shortner')]]))

#===============================================================#

@Client.on_callback_query(filters.regex("^rm_shortner$"))
async def rm_shortner(client: Client, query: CallbackQuery):
    if not query.from_user.id in client.admins:
        return await query.answer('❌ ᴏɴʟʏ ᴀᴅᴍɪɴꜱ ᴄᴀɴ ᴜꜱᴇ ᴛʜɪꜱ!', show_alert=True)

    await query.answer()

    shorteners = getattr(client, 'shorteners', {}) or {}
    if not shorteners:
        return await query.message.edit_text("**✗ ɴᴏ ꜱʜᴏʀᴛɴᴇʀꜱ ᴛᴏ ʀᴇᴍᴏᴠᴇ!**",
                                             reply_markup=InlineKeyboardMarkup([[InlineKeyboardButton('◂ ʙᴀᴄᴋ', 'shortner')]]))

    active_name = getattr(client, 'active_shortener', None)
    listing = "\n".join(f"{'✓' if n == active_name else '•'} `{n}`" for n in shorteners)
    msg = f"""<blockquote>**ʀᴇᴍᴏᴠᴇ ꜱʜᴏʀᴛɴᴇʀ:**</blockquote>
**ᴀᴠᴀɪʟᴀʙʟᴇ ꜱʜᴏʀᴛɴᴇʀꜱ:**
{listing}

__ꜱᴇɴᴅ ᴛʜᴇ ɴᴀᴍᴇ ᴏꜰ ᴛʜᴇ ꜱʜᴏʀᴛɴᴇʀ ᴛᴏ ʀᴇᴍᴏᴠᴇ ɪɴ ᴛʜᴇ ɴᴇxᴛ 60 ꜱᴇᴄᴏɴᴅꜱ!__"""

    await query.message.edit_text(msg)
    try:
        res = await client.listen(user_id=query.from_user.id, filters=filters.text, timeout=60)
        name = res.text.strip().lower()
        if name not in shorteners:
            return await query.message.edit_text(f"**✗ ꜱʜᴏʀᴛɴᴇʀ `{name}` ɴᴏᴛ ꜰᴏᴜɴᴅ!**",
                                                 reply_markup=InlineKeyboardMarkup([[InlineKeyboardButton('◂ ʙᴀᴄᴋ', 'shortner')]]))
        del client.shorteners[name]

        if client.active_shortener == name:
            remaining = list(client.shorteners.keys())
            client.active_shortener = remaining[0] if remaining else None

        shortened_urls_cache.clear()
        await save_shorteners(client)
        await query.message.edit_text(f"**✓ ʀᴇᴍᴏᴠᴇᴅ ꜱʜᴏʀᴛɴᴇʀ `{name}`!**\n**ᴀᴄᴛɪᴠᴇ ɴᴏᴡ:** `{client.active_shortener or 'ɴᴏɴᴇ'}`",
                                      reply_markup=InlineKeyboardMarkup([[InlineKeyboardButton('◂ ʙᴀᴄᴋ', 'shortner')]]))
    except ListenerTimeout:
        await query.message.edit_text("**⏰ ᴛɪᴍᴇᴏᴜᴛ! ᴛʀʏ ᴀɢᴀɪɴ.**",
                                    reply_markup=InlineKeyboardMarkup([[InlineKeyboardButton('◂ ʙᴀᴄᴋ', 'shortner')]]))

#===============================================================#

@Client.on_callback_query(filters.regex("^set_tutorial_link$"))
async def set_tutorial_link(client: Client, query: CallbackQuery):
    if not query.from_user.id in client.admins:
        return await query.answer('❌ ᴏɴʟʏ ᴀᴅᴍɪɴꜱ ᴄᴀɴ ᴜꜱᴇ ᴛʜɪꜱ!', show_alert=True)

    await query.answer()

    active_name = getattr(client, 'active_shortener', None)
    active_cfg = get_active_shortener(client)
    if not active_cfg:
        return await query.message.edit_text("**✗ ɴᴏ ᴀᴄᴛɪᴠᴇ ꜱʜᴏʀᴛɴᴇʀ! ᴀᴅᴅ ᴏʀ ꜱᴡɪᴛᴄʜ ᴛᴏ ᴏɴᴇ ꜰɪʀꜱᴛ.**",
                                             reply_markup=InlineKeyboardMarkup([[InlineKeyboardButton('◂ ʙᴀᴄᴋ', 'shortner')]]))

    current_tutorial = active_cfg.get('tutorial_link', 'ɴᴏᴛ ꜱᴇᴛ')
    msg = f"""<blockquote>**ꜱᴇᴛ ᴛᴜᴛᴏʀɪᴀʟ ʟɪɴᴋ ꜰᴏʀ `{active_name}`:**</blockquote>
**ᴄᴜʀʀᴇɴᴛ ᴛᴜᴛᴏʀɪᴀʟ:** `{current_tutorial}`

__ꜱᴇɴᴅ ᴛʜᴇ ɴᴇᴡ ᴛᴜᴛᴏʀɪᴀʟ ʟɪɴᴋ ɪɴ ᴛʜᴇ ɴᴇxᴛ 60 ꜱᴇᴄᴏɴᴅꜱ!__
**ᴇxᴀᴍᴘʟᴇ:** `https://t.me/How_to_Download_7x/26`"""

    await query.message.edit_text(msg)
    try:
        res = await client.listen(user_id=query.from_user.id, filters=filters.text, timeout=60)
        new_tutorial = res.text.strip()

        if new_tutorial and (new_tutorial.startswith('https://') or new_tutorial.startswith('http://')):
            client.shorteners[active_name]['tutorial_link'] = new_tutorial
            await save_shorteners(client)
            await query.message.edit_text(f"**✓ ᴛᴜᴛᴏʀɪᴀʟ ʟɪɴᴋ ꜰᴏʀ `{active_name}` ᴜᴘᴅᴀᴛᴇᴅ!**",
                                        reply_markup=InlineKeyboardMarkup([[InlineKeyboardButton('◂ ʙᴀᴄᴋ', 'shortner')]]))
        else:
            await query.message.edit_text("**✗ ɪɴᴠᴀʟɪᴅ ʟɪɴᴋ ꜰᴏʀᴍᴀᴛ! ᴍᴜꜱᴛ ꜱᴛᴀʀᴛ ᴡɪᴛʜ https:// ᴏʀ http://**",
                                        reply_markup=InlineKeyboardMarkup([[InlineKeyboardButton('◂ ʙᴀᴄᴋ', 'shortner')]]))
    except ListenerTimeout:
        await query.message.edit_text("**⏰ ᴛɪᴍᴇᴏᴜᴛ! ᴛʀʏ ᴀɢᴀɪɴ.**",
                                    reply_markup=InlineKeyboardMarkup([[InlineKeyboardButton('◂ ʙᴀᴄᴋ', 'shortner')]]))

#===============================================================#

@Client.on_callback_query(filters.regex("^test_shortner$"))
async def test_shortner(client: Client, query: CallbackQuery):
    if not query.from_user.id in client.admins:
        return await query.answer('❌ ᴏɴʟʏ ᴀᴅᴍɪɴꜱ ᴄᴀɴ ᴜꜱᴇ ᴛʜɪꜱ!', show_alert=True)

    await query.answer()

    active_name = getattr(client, 'active_shortener', None)
    active_cfg = get_active_shortener(client)
    if not active_cfg:
        return await query.message.edit_text("**✗ ɴᴏ ᴀᴄᴛɪᴠᴇ ꜱʜᴏʀᴛɴᴇʀ ᴛᴏ ᴛᴇꜱᴛ!**",
                                             reply_markup=InlineKeyboardMarkup([[InlineKeyboardButton('◂ ʙᴀᴄᴋ', 'shortner')]]))

    await query.message.edit_text(f"**🔄 ᴛᴇꜱᴛɪɴɢ ꜱʜᴏʀᴛɴᴇʀ `{active_name}`...**")

    short_url = active_cfg.get('url', SHORT_URL)
    short_api = active_cfg.get('api', SHORT_API)

    try:
        test_url = "https://google.com"
        alias = generate_random_alphanumeric()
        api_url = f"https://{short_url}/api?api={short_api}&url={test_url}&alias={alias}"

        response = requests.get(api_url, timeout=10)
        rjson = response.json()

        if rjson.get("status") == "success" and response.status_code == 200:
            short_link = rjson.get("shortenedUrl", "")
            msg = f"""**✅ ꜱʜᴏʀᴛɴᴇʀ `{active_name}` ᴛᴇꜱᴛ ꜱᴜᴄᴄᴇꜱꜱꜰᴜʟ!**

**ᴛᴇꜱᴛ ᴜʀʟ:** `{test_url}`
**ꜱʜᴏʀᴛ ᴜʀʟ:** `{short_link}`
**ʀᴇꜱᴘᴏɴꜱᴇ:** `{rjson.get('status', 'Unknown')}`"""
        else:
            msg = f"""**❌ ꜱʜᴏʀᴛɴᴇʀ `{active_name}` ᴛᴇꜱᴛ ꜰᴀɪʟᴇᴅ!**

**ᴇʀʀᴏʀ:** `{rjson.get('message', 'Unknown error')}`
**ꜱᴛᴀᴛᴜꜱ ᴄᴏᴅᴇ:** `{response.status_code}`"""

    except Exception as e:
        msg = f"**❌ ꜱʜᴏʀᴛɴᴇʀ `{active_name}` ᴛᴇꜱᴛ ꜰᴀɪʟᴇᴅ!**\n\n**ᴇʀʀᴏʀ:** `{str(e)}`"

    await query.message.edit_text(msg, reply_markup=InlineKeyboardMarkup([[InlineKeyboardButton('◂ ʙᴀᴄᴋ', 'shortner')]]))

#===============================================================#
# Auto Mode — separate ordered shortner list, cycles one at a time
# per-user, shared across all bots on this database, resets daily
# at 12 AM India time.
#===============================================================#

async def save_auto_shorteners(client):
    """Persist client.auto_shorteners + client.auto_shortener_enabled to the DB."""
    await client.mongodb.update_auto_shortner_setting('shorteners', client.auto_shorteners, client.bot_id)
    await client.mongodb.update_auto_shortner_setting('enabled', client.auto_shortener_enabled, client.bot_id)

async def auto_shortner_panel(client, query_or_message):
    auto_list = getattr(client, 'auto_shorteners', []) or []
    auto_enabled = getattr(client, 'auto_shortener_enabled', False)

    enabled_text = "✓ ᴇɴᴀʙʟᴇᴅ" if auto_enabled else "✗ ᴅɪsᴀʙʟᴇᴅ"
    toggle_text = "✗ ᴏғғ" if auto_enabled else "✓ ᴏɴ"

    if auto_list:
        lines = []
        for i, cfg in enumerate(auto_list, start=1):
            lines.append(f"**{i}.** `{cfg.get('url', '?')}`")
        list_display = "\n".join(lines)
    else:
        list_display = "_ɴᴏ ᴀᴜᴛᴏ ʟɪɴᴋs ᴀᴅᴅᴇᴅ ʏᴇᴛ_"

    msg = f"""<blockquote>✦ 𝗔𝗨𝗧𝗢 𝗠𝗢𝗗𝗘 𝗦𝗘𝗧𝗧𝗜𝗡𝗚𝗦</blockquote>
**<u>ꜱᴛᴀᴛᴜꜱ:</u>** {enabled_text}

**<u>ʜᴏᴡ ɪᴛ ᴡᴏʀᴋs:</u>**
<blockquote>Wʜᴇɴ ᴏɴ, ᴇᴀᴄʜ ᴜsᴇʀ ɪs sʜᴏᴡɴ ᴏɴᴇ ʟɪɴᴋ ꜰʀᴏᴍ ᴛʜᴇ ʟɪsᴛ ʙᴇʟᴏᴡ ᴀᴛ ᴀ ᴛɪᴍᴇ. Sᴏʟᴠɪɴɢ ɪᴛ ᴍᴏᴠᴇs ᴛʜᴇᴍ ᴛᴏ ᴛʜᴇ ɴᴇxᴛ ʟɪɴᴋ, ᴡʀᴀᴘᴘɪɴɢ ʙᴀᴄᴋ ᴛᴏ #1 ᴀꜰᴛᴇʀ ᴛʜᴇ ʟᴀꜱᴛ. Tʜᴇ ᴄʏᴄʟᴇ ᴀʟsᴏ ʀᴇsᴇᴛs ᴛᴏ #1 ᴇᴠᴇʀʏ ᴅᴀʏ ᴀᴛ 12 AM IST, ᴀɴᴅ ɪs sʜᴀʀᴇᴅ ᴀᴄʀᴏss ᴀʟʟ ʙᴏᴛs ᴏɴ ᴛʜɪs ᴅᴀᴛᴀʙᴀsᴇ ꜰᴏʀ ᴛʜᴇ sᴀᴍᴇ ᴜsᴇʀ.</blockquote>

**<u>ᴀᴜᴛᴏ ʟɪɴᴋs ({len(auto_list)}):</u>**
<blockquote>{list_display}</blockquote>

<blockquote>**Nᴏᴛᴇ:** Wʜᴇɴ ᴀᴜᴛᴏ ᴍᴏᴅᴇ ɪs ᴏɴ, ɪᴛ ᴏᴠᴇʀʀɪᴅᴇs ᴛʜᴇ ʀᴇɢᴜʟᴀʀ sʜᴏʀᴛɴᴇʀ ᴀʙᴏᴠᴇ ꜰᴏʀ ɴᴇᴡ ꜰɪʟᴇ ʟɪɴᴋs.**</blockquote>"""

    reply_markup = InlineKeyboardMarkup([
        [InlineKeyboardButton(f'• {toggle_text} ᴀᴜᴛᴏ ᴍᴏᴅᴇ •', 'toggle_auto_shortner')],
        [InlineKeyboardButton('• ᴀᴅᴅ ʟɪɴᴋ •', 'add_auto_shortner'), InlineKeyboardButton('• ʀᴇᴍᴏᴠᴇ ʟɪɴᴋ •', 'rm_auto_shortner')],
        [InlineKeyboardButton('• ᴇᴅɪᴛ ʟɪɴᴋ •', 'edit_auto_shortner'), InlineKeyboardButton('• ʀᴇᴏʀᴅᴇʀ ʟɪɴᴋ •', 'move_auto_shortner')],
        [InlineKeyboardButton('◂ ʙᴀᴄᴋ', 'shortner')]
    ])

    if hasattr(query_or_message, 'message'):
        await query_or_message.message.edit_text(msg, reply_markup=reply_markup)
    else:
        await query_or_message.reply_text(msg, reply_markup=reply_markup)

#===============================================================#

@Client.on_callback_query(filters.regex("^auto_shortner$"))
async def auto_shortner_callback(client, query):
    if not query.from_user.id in client.admins:
        return await query.answer('❌ ᴏɴʟʏ ᴀᴅᴍɪɴꜱ ᴄᴀɴ ᴜꜱᴇ ᴛʜɪꜱ!', show_alert=True)
    await query.answer()
    await auto_shortner_panel(client, query)

#===============================================================#

@Client.on_callback_query(filters.regex("^toggle_auto_shortner$"))
async def toggle_auto_shortner(client: Client, query: CallbackQuery):
    if not query.from_user.id in client.admins:
        return await query.answer('❌ ᴏɴʟʏ ᴀᴅᴍɪɴꜱ ᴄᴀɴ ᴜꜱᴇ ᴛʜɪꜱ!', show_alert=True)

    new_status = not getattr(client, 'auto_shortener_enabled', False)
    client.auto_shortener_enabled = new_status
    await client.mongodb.update_auto_shortner_setting('enabled', new_status, client.bot_id)

    status_text = "ᴇɴᴀʙʟᴇᴅ" if new_status else "ᴅɪsᴀʙʟᴇᴅ"
    await query.answer(f"✓ ᴀᴜᴛᴏ ᴍᴏᴅᴇ {status_text}!")
    await auto_shortner_panel(client, query)

#===============================================================#

@Client.on_callback_query(filters.regex("^add_auto_shortner$"))
async def add_auto_shortner(client: Client, query: CallbackQuery):
    if not query.from_user.id in client.admins:
        return await query.answer('❌ ᴏɴʟʏ ᴀᴅᴍɪɴꜱ ᴄᴀɴ ᴜꜱᴇ ᴛʜɪꜱ!', show_alert=True)

    await query.answer()

    auto_list = getattr(client, 'auto_shorteners', []) or []
    msg = f"""<blockquote>**ᴀᴅᴅ ᴀ ʟɪɴᴋ ᴛᴏ ᴀᴜᴛᴏ ᴍᴏᴅᴇ (ᴡɪʟʟ ʙᴇᴄᴏᴍᴇ #{len(auto_list) + 1}):**</blockquote>

__<blockquote>**≡ ꜱᴇɴᴅ ᴛʜᴇ ɴᴇᴡ ʟɪɴᴋ ɪɴ ᴛʜɪꜱ ꜰᴏʀᴍᴀᴛ ɪɴ ᴛʜᴇ ɴᴇxᴛ 90 ꜱᴇᴄᴏɴᴅꜱ!**</blockquote>__

**ꜰᴏʀᴍᴀᴛ:** `url api tutorial_link`
**ᴇxᴀᴍᴘʟᴇ:** `gplinks.in 9435894656863495834957348 https://t.me/How_to_Download_7x/26`"""

    await query.message.edit_text(msg)
    try:
        res = await client.listen(user_id=query.from_user.id, filters=filters.text, timeout=90)
        response_text = res.text.strip()

        parts = response_text.split()
        if len(parts) == 3:
            raw_url, api, tutorial_link = parts
            new_url = raw_url.replace('https://', '').replace('http://', '').replace('/', '')

            valid = (
                new_url and '.' in new_url
                and api and len(api) > 10
                and (tutorial_link.startswith('https://') or tutorial_link.startswith('http://'))
            )

            if valid:
                if not hasattr(client, 'auto_shorteners'):
                    client.auto_shorteners = []
                client.auto_shorteners.append({'url': new_url, 'api': api, 'tutorial_link': tutorial_link})
                await save_auto_shorteners(client)

                await query.message.edit_text(
                    f"**✓ ᴀᴅᴅᴇᴅ ᴀꜱ ʟɪɴᴋ #{len(client.auto_shorteners)}!**\n\n**ᴜʀʟ:** `{new_url}`",
                    reply_markup=InlineKeyboardMarkup([[InlineKeyboardButton('◂ ʙᴀᴄᴋ', 'auto_shortner')]])
                )
            else:
                await query.message.edit_text("**✗ ɪɴᴠᴀʟɪᴅ ꜰᴏʀᴍᴀᴛ! ᴄʜᴇᴄᴋ ᴜʀʟ/ᴀᴘɪ/ᴛᴜᴛᴏʀɪᴀʟ ʟɪɴᴋ.**",
                                              reply_markup=InlineKeyboardMarkup([[InlineKeyboardButton('◂ ʙᴀᴄᴋ', 'auto_shortner')]]))
        else:
            await query.message.edit_text("**✗ ɪɴᴠᴀʟɪᴅ ꜰᴏʀᴍᴀᴛ! ᴜꜱᴇ: `url api tutorial_link`**",
                                          reply_markup=InlineKeyboardMarkup([[InlineKeyboardButton('◂ ʙᴀᴄᴋ', 'auto_shortner')]]))
    except ListenerTimeout:
        await query.message.edit_text("**⏰ ᴛɪᴍᴇᴏᴜᴛ! ᴛʀʏ ᴀɢᴀɪɴ.**",
                                    reply_markup=InlineKeyboardMarkup([[InlineKeyboardButton('◂ ʙᴀᴄᴋ', 'auto_shortner')]]))

#===============================================================#

@Client.on_callback_query(filters.regex("^rm_auto_shortner$"))
async def rm_auto_shortner(client: Client, query: CallbackQuery):
    if not query.from_user.id in client.admins:
        return await query.answer('❌ ᴏɴʟʏ ᴀᴅᴍɪɴꜱ ᴄᴀɴ ᴜꜱᴇ ᴛʜɪꜱ!', show_alert=True)

    await query.answer()

    auto_list = getattr(client, 'auto_shorteners', []) or []
    if not auto_list:
        return await query.message.edit_text("**✗ ɴᴏ ᴀᴜᴛᴏ ʟɪɴᴋs ᴛᴏ ʀᴇᴍᴏᴠᴇ!**",
                                             reply_markup=InlineKeyboardMarkup([[InlineKeyboardButton('◂ ʙᴀᴄᴋ', 'auto_shortner')]]))

    listing = "\n".join(f"**{i}.** `{cfg.get('url', '?')}`" for i, cfg in enumerate(auto_list, start=1))
    msg = f"""<blockquote>**ʀᴇᴍᴏᴠᴇ ᴀᴜᴛᴏ ʟɪɴᴋ:**</blockquote>
{listing}

__ꜱᴇɴᴅ ᴛʜᴇ ɴᴜᴍʙᴇʀ ᴏꜰ ᴛʜᴇ ʟɪɴᴋ ᴛᴏ ʀᴇᴍᴏᴠᴇ ɪɴ ᴛʜᴇ ɴᴇxᴛ 60 ꜱᴇᴄᴏɴᴅꜱ!__"""

    await query.message.edit_text(msg)
    try:
        res = await client.listen(user_id=query.from_user.id, filters=filters.text, timeout=60)
        raw = res.text.strip()
        if not raw.isdigit() or not (1 <= int(raw) <= len(auto_list)):
            return await query.message.edit_text(f"**✗ ɪɴᴠᴀʟɪᴅ ɴᴜᴍʙᴇʀ! ᴘɪᴄᴋ 1-{len(auto_list)}.**",
                                                 reply_markup=InlineKeyboardMarkup([[InlineKeyboardButton('◂ ʙᴀᴄᴋ', 'auto_shortner')]]))
        idx = int(raw) - 1
        removed = client.auto_shorteners.pop(idx)
        await save_auto_shorteners(client)
        await query.message.edit_text(f"**✓ ʀᴇᴍᴏᴠᴇᴅ `{removed.get('url', '?')}`!**\n**ʀᴇᴍᴀɪɴɪɴɢ:** `{len(client.auto_shorteners)}`",
                                      reply_markup=InlineKeyboardMarkup([[InlineKeyboardButton('◂ ʙᴀᴄᴋ', 'auto_shortner')]]))
    except ListenerTimeout:
        await query.message.edit_text("**⏰ ᴛɪᴍᴇᴏᴜᴛ! ᴛʀʏ ᴀɢᴀɪɴ.**",
                                    reply_markup=InlineKeyboardMarkup([[InlineKeyboardButton('◂ ʙᴀᴄᴋ', 'auto_shortner')]]))

#===============================================================#

@Client.on_callback_query(filters.regex("^edit_auto_shortner$"))
async def edit_auto_shortner(client: Client, query: CallbackQuery):
    if not query.from_user.id in client.admins:
        return await query.answer('❌ ᴏɴʟʏ ᴀᴅᴍɪɴꜱ ᴄᴀɴ ᴜꜱᴇ ᴛʜɪꜱ!', show_alert=True)

    await query.answer()

    auto_list = getattr(client, 'auto_shorteners', []) or []
    if not auto_list:
        return await query.message.edit_text("**✗ ɴᴏ ᴀᴜᴛᴏ ʟɪɴᴋs ᴛᴏ ᴇᴅɪᴛ!**",
                                             reply_markup=InlineKeyboardMarkup([[InlineKeyboardButton('◂ ʙᴀᴄᴋ', 'auto_shortner')]]))

    listing = "\n".join(f"**{i}.** `{cfg.get('url', '?')}`" for i, cfg in enumerate(auto_list, start=1))
    msg = f"""<blockquote>**ᴇᴅɪᴛ ᴀᴜᴛᴏ ʟɪɴᴋ:**</blockquote>
{listing}

__ꜱᴇɴᴅ ᴛʜᴇ ɴᴜᴍʙᴇʀ ᴏꜰ ᴛʜᴇ ʟɪɴᴋ ᴛᴏ ᴇᴅɪᴛ ɪɴ ᴛʜᴇ ɴᴇxᴛ 60 ꜱᴇᴄᴏɴᴅꜱ!__"""

    await query.message.edit_text(msg)
    try:
        res = await client.listen(user_id=query.from_user.id, filters=filters.text, timeout=60)
        raw = res.text.strip()
        if not raw.isdigit() or not (1 <= int(raw) <= len(auto_list)):
            return await query.message.edit_text(f"**✗ ɪɴᴠᴀʟɪᴅ ɴᴜᴍʙᴇʀ! ᴘɪᴄᴋ 1-{len(auto_list)}.**",
                                                 reply_markup=InlineKeyboardMarkup([[InlineKeyboardButton('◂ ʙᴀᴄᴋ', 'auto_shortner')]]))
        idx = int(raw) - 1
        current = auto_list[idx]

        msg2 = f"""<blockquote>**ᴇᴅɪᴛɪɴɢ ʟɪɴᴋ #{idx + 1}:**</blockquote>
**ᴄᴜʀʀᴇɴᴛ ᴜʀʟ:** `{current.get('url', '?')}`
**ᴄᴜʀʀᴇɴᴛ ᴀᴘɪ:** `{(current.get('api', '')[:20] + '...') if current.get('api') else 'ɴᴏᴛ ꜱᴇᴛ'}`
**ᴄᴜʀʀᴇɴᴛ ᴛᴜᴛᴏʀɪᴀʟ:** `{current.get('tutorial_link', 'ɴᴏᴛ ꜱᴇᴛ')}`

__<blockquote>**≡ ꜱᴇɴᴅ ᴛʜᴇ ɴᴇᴡ ᴅᴇᴛᴀɪʟs ɪɴ ᴛʜɪꜱ ꜰᴏʀᴍᴀᴛ ɪɴ ᴛʜᴇ ɴᴇxᴛ 90 ꜱᴇᴄᴏɴᴅꜱ!**</blockquote>__

**ꜰᴏʀᴍᴀᴛ:** `url api tutorial_link`
**ᴇxᴀᴍᴘʟᴇ:** `gplinks.in 9435894656863495834957348 https://t.me/How_to_Download_7x/26`"""

        await query.message.edit_text(msg2)
        res2 = await client.listen(user_id=query.from_user.id, filters=filters.text, timeout=90)
        response_text = res2.text.strip()

        parts = response_text.split()
        if len(parts) == 3:
            raw_url, api, tutorial_link = parts
            new_url = raw_url.replace('https://', '').replace('http://', '').replace('/', '')

            valid = (
                new_url and '.' in new_url
                and api and len(api) > 10
                and (tutorial_link.startswith('https://') or tutorial_link.startswith('http://'))
            )

            if valid:
                client.auto_shorteners[idx] = {'url': new_url, 'api': api, 'tutorial_link': tutorial_link}
                await save_auto_shorteners(client)

                await query.message.edit_text(
                    f"**✓ ᴜᴘᴅᴀᴛᴇᴅ ʟɪɴᴋ #{idx + 1}!**\n\n**ᴜʀʟ:** `{new_url}`",
                    reply_markup=InlineKeyboardMarkup([[InlineKeyboardButton('◂ ʙᴀᴄᴋ', 'auto_shortner')]])
                )
            else:
                await query.message.edit_text("**✗ ɪɴᴠᴀʟɪᴅ ꜰᴏʀᴍᴀᴛ! ᴄʜᴇᴄᴋ ᴜʀʟ/ᴀᴘɪ/ᴛᴜᴛᴏʀɪᴀʟ ʟɪɴᴋ.**",
                                              reply_markup=InlineKeyboardMarkup([[InlineKeyboardButton('◂ ʙᴀᴄᴋ', 'auto_shortner')]]))
        else:
            await query.message.edit_text("**✗ ɪɴᴠᴀʟɪᴅ ꜰᴏʀᴍᴀᴛ! ᴜꜱᴇ: `url api tutorial_link`**",
                                          reply_markup=InlineKeyboardMarkup([[InlineKeyboardButton('◂ ʙᴀᴄᴋ', 'auto_shortner')]]))
    except ListenerTimeout:
        await query.message.edit_text("**⏰ ᴛɪᴍᴇᴏᴜᴛ! ᴛʀʏ ᴀɢᴀɪɴ.**",
                                    reply_markup=InlineKeyboardMarkup([[InlineKeyboardButton('◂ ʙᴀᴄᴋ', 'auto_shortner')]]))

#===============================================================#

@Client.on_callback_query(filters.regex("^move_auto_shortner$"))
async def move_auto_shortner(client: Client, query: CallbackQuery):
    """Reorder an auto link — lets an admin change which position number (#1, #2, ...) a link sits at."""
    if not query.from_user.id in client.admins:
        return await query.answer('❌ ᴏɴʟʏ ᴀᴅᴍɪɴꜱ ᴄᴀɴ ᴜꜱᴇ ᴛʜɪꜱ!', show_alert=True)

    await query.answer()

    auto_list = getattr(client, 'auto_shorteners', []) or []
    if len(auto_list) < 2:
        return await query.message.edit_text("**✗ ɴᴇᴇᴅ ᴀᴛ ʟᴇᴀꜱᴛ 2 ʟɪɴᴋs ᴛᴏ ʀᴇᴏʀᴅᴇʀ!**",
                                             reply_markup=InlineKeyboardMarkup([[InlineKeyboardButton('◂ ʙᴀᴄᴋ', 'auto_shortner')]]))

    listing = "\n".join(f"**{i}.** `{cfg.get('url', '?')}`" for i, cfg in enumerate(auto_list, start=1))
    msg = f"""<blockquote>**ʀᴇᴏʀᴅᴇʀ ᴀᴜᴛᴏ ʟɪɴᴋ:**</blockquote>
{listing}

__ꜱᴇɴᴅ ᴛʜᴇ ᴄᴜʀʀᴇɴᴛ ɴᴜᴍʙᴇʀ ᴀɴᴅ ᴛʜᴇ ɴᴇᴡ ɴᴜᴍʙᴇʀ, ꜱᴇᴘᴀʀᴀᴛᴇᴅ ʙʏ ᴀ ꜱᴘᴀᴄᴇ (ᴇ.ɢ. `3 1`), ɪɴ ᴛʜᴇ ɴᴇxᴛ 60 ꜱᴇᴄᴏɴᴅꜱ!__"""

    await query.message.edit_text(msg)
    try:
        res = await client.listen(user_id=query.from_user.id, filters=filters.text, timeout=60)
        parts = res.text.strip().split()
        if (
            len(parts) == 2 and all(p.isdigit() for p in parts)
            and 1 <= int(parts[0]) <= len(auto_list) and 1 <= int(parts[1]) <= len(auto_list)
        ):
            from_idx, to_idx = int(parts[0]) - 1, int(parts[1]) - 1
            item = client.auto_shorteners.pop(from_idx)
            client.auto_shorteners.insert(to_idx, item)
            await save_auto_shorteners(client)
            await query.message.edit_text(
                f"**✓ ᴍᴏᴠᴇᴅ `{item.get('url', '?')}` ᴛᴏ #{to_idx + 1}!**",
                reply_markup=InlineKeyboardMarkup([[InlineKeyboardButton('◂ ʙᴀᴄᴋ', 'auto_shortner')]])
            )
        else:
            await query.message.edit_text(f"**✗ ɪɴᴠᴀʟɪᴅ! ꜱᴇɴᴅ ᴛᴡᴏ ɴᴜᴍʙᴇʀꜱ ʙᴇᴛᴡᴇᴇɴ 1-{len(auto_list)}, ᴇ.ɢ. `3 1`.**",
                                          reply_markup=InlineKeyboardMarkup([[InlineKeyboardButton('◂ ʙᴀᴄᴋ', 'auto_shortner')]]))
    except ListenerTimeout:
        await query.message.edit_text("**⏰ ᴛɪᴍᴇᴏᴜᴛ! ᴛʀʏ ᴀɢᴀɪɴ.**",
                                    reply_markup=InlineKeyboardMarkup([[InlineKeyboardButton('◂ ʙᴀᴄᴋ', 'auto_shortner')]]))
